### ISSUE TITLE
another problem with spacy on : https://www.kaggle.com/code/smoestergaard/some-s22-reddit-toolbox/notebook 

### ISSUE THREAD

**Issue by S-Hahemi222** [KennethEnevoldsen/asent#130]
hi 

 when i run the second box (the box which entitled "#Load packages" ) on https://www.kaggle.com/code/smoestergaard/some-s22-reddit-toolbox/notebook,  i receive a new error :
<img width="960" alt="ken1" src="https://user-images.githubusercontent.com/132681672/236521171-8f950d16-5d35-400f-a553-a6d91687af1c.png">
![ken2](https://user-images.githubusercontent.com/132681672/236521204-b4e65f9f-832f-4e28-ae00-d7d64ac78a08.jpg)

![ken3](https://user-images.githubusercontent.com/132681672/236521526-d3199e61-35a2-4998-9ac0-3ed23872bf2a.jpg)

what should i do ?

**Comment by KennethEnevoldsen** [comment]
Hi @S-Hahemi222, again this does not seem to be a bug so I would recommend using the discussion forum. It also does not seems like a bug with asent (you seem to not be using asent as it is commented out in the code). 

Generally, when you use these types of fora it  first has to show what causes the problem in a way minimally reproducible fashion. This [post](https://stackoverflow.com/help/minimal-reproducible-example) here can help you get started.
