### ISSUE TITLE
Option to save output from `asent.visualize`

### ISSUE THREAD

**Issue by HLasse** [KennethEnevoldsen/asent#133]
It would be neat to have the option to save the output of a visualization to a svg/png to use for presentations/papers. Currently, the methods return None, and screenshotting the output tends to produce quite low-resolution images.

**Comment by KennethEnevoldsen** [comment]
It actually return object from spacy.render. Which you can save using:

```python
import spacy
from spacy import displacy
from pathlib import Path
import asent

nlp = spacy.load('en_core_web_sm')
nlp.add_pipe("asent_en_v1")

doc = nlp("John is very sad")

# save viz
svg = asent.visualize(doc, style="analysis")
output_path = Path("sent_analysis.svg")
output_path.open("w", encoding="utf-8").write(svg)
```

You just can't save it a notebook where it returns None.
