### ISSUE TITLE
Question - Set minimum threshold

### ISSUE THREAD

**Issue by sabatale** [KennethEnevoldsen/asent#149]
Great library! Apologies for the questions in one.

This is what we get and see in the docs:
![image](https://github.com/KennethEnevoldsen/asent/assets/50220345/0d2f8e21-22d5-4490-b8ba-f60141c2baaf)

Is there a way to exclude anything that is below Math.abs(1.5) for example? In that example, we would ignore both labels. The main idea is to identify n-grams (e.g., 3+ words) with a single label as very positive or very negative feedbacks.

Besides, from a style perspective, we saw this one as well. Assuming this is an old theme, is there an option to set it?
![image](https://github.com/KennethEnevoldsen/asent/assets/50220345/05dcff21-e6d0-462f-87a2-c0604a84662e)

The idea would be to merge it with displacy entities rendering and the style is much more similar.

**Comment by KennethEnevoldsen** [comment]
Glad you enjoy the package! Hope you find it useful.

So two question and a oddity:

**Q1. Is there a way to filter below a certain threshold:**
Not currently. One solution would be to filter the "span._.polarity" object, however as everything is calculated on the fly atm (in case anything change in the sentence you will never have an "outdated" sentiment). I have actually considered from a getter to a setter  (which would allow you to filter that object, but would mean that if you change the document object, the sentiment would not change in accordance). Would that work for your use-case?

**Q2. How can I get the "old" style** 
you can get it using: style="prediction-no-overlap". The interface is documented [here](https://kennethenevoldsen.github.io/asent/asent.visualize.html). Although I see that some examples could be added to make it more clear what you get. However do note that it does not allow for overlapping sentiment spans (in which case it leads to duplicate words).


**Oddity**:
generally "no", "matter" shouldn't be considered a positive or negative.

I have checked it the lexicon:

Matter is rated slightly positive once, but otherswise rated as 0 (neutral):
```
matter	0.1	0.3	[0, 0, 0, 0, 0, 0, 0, 1, 0, 0]
``` 

Rating like these might be the reason why you are getting some fairly odd ratings a better solution than filtering the visualizer might be to filter the lexicon (a heuristic could be if it rated lower than 1.0 and the most common rating is 0 I would delete it from the lexicon).

**Comment by sabatale** [comment]
That would take a bit of thinking but I'd say we would still appreciate having some type of filter, even though it may not get recalculated dynamically. It just feels reassuring to have option to "force" some of our own logic.

We already started customizing the lexicon as we had a similar experience with Vader, notably not handling n-grams. Thanks for the tip!

**Comment by KennethEnevoldsen** [comment]
Unsure if you meant to close this issue so will re-open it again additionally because I feel we can address the issue.

So sounds like Changing the doc.polarity to be mutable (and not dynamically calculated). A solution could look somewhat like this:
```
doc = nlp(your_example)

token_polarities = doc.polarity.polarities
token_polaritities = filter(your_filter_function, token_polarities)
doc.polarity.polarities = token_polaritities # update the object

asent.visualize(doc, ...)
```

Can you confirm that this would work for you?

**Comment by sabatale** [comment]
Others may have a different requirement but yes, that would do it!

**Comment by KennethEnevoldsen** [comment]
Sorry for the wait on this. I only just now noticed that you answered. I have fixed the issue. You can now filter the polarities like this:

```python

import spacy

import asent

# create spacy pipeline
nlp = spacy.blank("en")
nlp.add_pipe("sentencizer")

# add the rule-based sentiment model
nlp.add_pipe("asent_en_v1")

# try an example
text = "I am not very happy, but I am also not especially sad"
doc = nlp(text)

pol = doc._.polarity
span_pol = pol.as_span_polarity()

# an example filter
filtered_polarities = [pol for pol in span_pol.polarities if pol.polarity >= 1.0]
span_pol.polarities = filtered_polarities

asent.visualize(span_pol)
```
