### ISSUE TITLE
Wrong visualizations / valence scores for custom Asent component

### ISSUE THREAD

**Issue by tsmdt** [KennethEnevoldsen/asent#187]
Hi!

I am trying to get a custom Asent pipeline working with an older German Vader lexicon, but the visualizations and valence scores on my test sentences are wrong. I use the following lexicon that works fine with VaderGER: https://github.com/KarstenAMF/GerVADER/blob/master/GERVaderLexicon.txt

Here is my code:
```
import spacy
import asent
from asent.component import Asent
from asent import utils
from vaderPlus import VaderConstants

# load spacy pipeline
nlp = spacy.load("de_core_news_sm")

# Lexicon
lexicon_de = utils.read_lexicon('lexicons/GERVaderLexicon.txt')
print(lexicon_de)
```
...
'Blüten': 1.9,
'Bock': 1.3,
'Bombardement': -2.7,
'Bombardements': -2.7,
'Bombardierung': -2.9,
'Bombardierungen': -2.9,
'Bombe': -1.8,
'Bomben': -1.8,
'Bonität': 1.8,
'Bonitäten': 1.8
...
```
# Intensifiers
intensifiers_de = VaderConstants(language='de').BOOSTER_DICT
print(intensifiers_de)
```
{'absolut': 0.293, 'total': 0.293, 'unbedingt': 0.293, 'erstaunlich': 0.293, 'enorm': 0.293, ...

```
# Negations
negations_de = VaderConstants(language='de').NEGATE
print(negations_de)
```
{'kaum',
 'keine',
 'never',
 'nicht',
 'nichts',
...

```
Asent(
    nlp, 
    name="asent_de", 
    lexicon=lexicon_de, 
    intensifiers=intensifiers_de, 
    negations=negations_de, 
    lowercase=False, 
    lemmatize=False
)

# test it out and visualize results
doc = nlp("Ich fühle mich nicht sehr gut.")
asent.visualize(doc)
```
<img width="240" alt="image" src="https://github.com/user-attachments/assets/a0dd7930-6866-4c83-a3dd-a9dafdff3388">

As you can see there is no visualization although "gut" with the intensifier "sehr" and the negation "nicht" are present. If I print the valence scores for the doc I get this:
```
for token in doc:
   print(token, "\t", token._.valence)
```
Ich 	 0.0
fühle 	 0.0
mich 	 0.0
nicht 	 0.0
sehr 	 0.0
gut 	 0.0
. 	 0.0

But when I print the valence for "gut" ("good") from the lexicon I get the correct score that is missing in the for loop:
```
lexicon_de.get('gut')
```
2.1

Do you have any idea what I could be doing wrong?

**Comment by tsmdt** [comment]
Don't know what I did wrong, but a fresh python env fixed the issue 😉

**Comment by KennethEnevoldsen** [comment]
Good to hear! The german dictionary looks quite nice! If you have the files I can add it as a part of the package (I would also very much welcome a pull-request if you want to become a contributor)
