### ISSUE TITLE
`nlp` gets incorrectly overwritten in Getting Started

### ISSUE THREAD

**Issue by tomaarsen** [KennethEnevoldsen/asent#55]
Hello!

The documentation page [Getting started](https://kennethenevoldsen.github.io/asent/introduction.html) has the following snippet:
```python
import asent
import spacy

# load spacy pipeline
nlp = spacy.load("en_core_web_lg")

# add the rule-based sentiment model
nlp = nlp.add_pipe("asent_en_v1")
```
As you likely know, [`add_pipe`](https://spacy.io/api/language#add_pipe) returns the pipeline component, and thus `nlp` is overwritten to `asent.component.Asent`, causing the remaining code snippets to fail. 

## Which page or section is this issue related to?
https://kennethenevoldsen.github.io/asent/introduction.html, each of the 4 language tabs

- Tom Aarsen

**Comment by KennethEnevoldsen** [comment]
Hi @tomaarsen, sorry for the late response on this. You are completely correct. I will merge in the PR.
