### ISSUE TITLE
NotImplementedError: [E111] Pickling a token is not supported

### ISSUE THREAD

**Issue by mutigaj1** [KennethEnevoldsen/asent#62]
![image](https://user-images.githubusercontent.com/39117687/187725207-769e90d0-0ff0-4d5b-b2f5-69f2b5f50700.png)
what is this error?

**Comment by KennethEnevoldsen** [comment]
I am not sure, when does it happen?

**Comment by KennethEnevoldsen** [comment]
As there hasn't been a response on this issue, I will close it. Feel free to open it.
